<?php
return [
    [
        'name' => 'Nabati Richeese Wafer Krim Keju',
        'desc' => 'Richeese Nabati Cheese Wafer merupakan cemilan lezat dan bergizi. Cemilan wafer rasa keju ini memiliki tekstur yang krispi dan renyah saat digigit.',
        'category' => 'Makanan',
        'brand' => 'Nabati',
        'price' => '2000',
        'qty' => '10',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Aqua Mineral Water 600ml',
        'desc' => 'Aqua Mineral Water is sourced from natural springs and processed with state-of-the-art technology to ensure purity and freshness.',
        'category' => 'Minuman',
        'brand' => 'Aqua',
        'price' => '3000',
        'qty' => '20',
        'status' => 'Out of Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Milo Drink',
        'desc' => 'Milo is a delicious chocolate malt drink that is loved by people of all ages.',
        'category' => 'Minuman',
        'brand' => 'Milo',
        'price' => '2500',
        'qty' => '15',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Apple',
        'desc' => 'Fresh apple sourced directly from orchards, perfect for a healthy snack or salad.',
        'category' => 'Produk Segar',
        'brand' => 'Apple Farms',
        'price' => '5000',
        'qty' => '30',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Dettol Antiseptic Liquid',
        'desc' => 'Dettol Antiseptic Liquid helps to kill germs and bacteria on skin and surfaces, providing protection for your family.',
        'category' => 'Produk Pembersih',
        'brand' => 'Dettol',
        'price' => '7000',
        'qty' => '25',
        'status' => 'Out of Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Vitamin C Tablets',
        'desc' => 'Vitamin C tablets provide a daily dose of essential nutrients to support your immune system and overall health.',
        'category' => 'Produk Kesehatan',
        'brand' => 'Health Plus',
        'price' => '10000',
        'qty' => '40',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Indomie Mi Goreng',
        'desc' => 'Indomie Mi Goreng is a popular instant noodle dish known for its delicious flavor and ease of preparation.',
        'category' => 'Makanan',
        'brand' => 'Indomie',
        'price' => '1500',
        'qty' => '50',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Teh Botol Sosro',
        'desc' => 'Teh Botol Sosro is a refreshing bottled tea drink made from high-quality tea leaves.',
        'category' => 'Minuman',
        'brand' => 'Sosro',
        'price' => '3500',
        'qty' => '30',
        'status' => 'Out of Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Coca-Cola',
        'desc' => 'Coca-Cola is a carbonated soft drink known for its refreshing taste and iconic branding.',
        'category' => 'Minuman',
        'brand' => 'Coca-Cola',
        'price' => '4000',
        'qty' => '20',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Carrots',
        'desc' => 'Fresh carrots are packed with vitamins and antioxidants, making them a nutritious addition to any meal.',
        'category' => 'Produk Segar',
        'brand' => 'Farm Fresh',
        'price' => '3000',
        'qty' => '35',
        'status' => 'Out of Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Colgate Total Toothpaste',
        'desc' => 'Colgate Total Toothpaste provides comprehensive protection against cavities, tartar, and plaque, leaving your teeth clean and healthy.',
        'category' => 'Produk Kesehatan',
        'brand' => 'Colgate',
        'price' => '8000',
        'qty' => '15',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Lays Potato Chips',
        'desc' => 'Lays Potato Chips are thinly sliced and lightly salted for a crispy and satisfying snack experience.',
        'category' => 'Makanan',
        'brand' => 'Lays',
        'price' => '1800',
        'qty' => '25',
        'status' => 'Out of Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Sprite',
        'desc' => 'Sprite is a lemon-lime flavored soda known for its crisp and refreshing taste.',
        'category' => 'Minuman',
        'brand' => 'Sprite',
        'price' => '3000',
        'qty' => '20',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Bananas',
        'desc' => 'Bananas are a nutritious fruit packed with potassium, fiber, and vitamins.',
        'category' => 'Produk Segar',
        'brand' => 'Farm Fresh',
        'price' => '4000',
        'qty' => '30',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Hand Sanitizer',
        'desc' => 'Hand sanitizer gel helps to kill germs and bacteria on hands when soap and water are not available.',
        'category' => 'Produk Pembersih',
        'brand' => 'Purell',
        'price' => '5000',
        'qty' => '20',
        'status' => 'Out of Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Paracetamol Tablets',
        'desc' => 'Paracetamol tablets are commonly used to relieve pain and reduce fever.',
        'category' => 'Produk Kesehatan',
        'brand' => 'Generic',
        'price' => '2000',
        'qty' => '35',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Potato',
        'desc' => 'Potatoes are a versatile vegetable that can be boiled, mashed, baked, or fried to create a variety of delicious dishes.',
        'category' => 'Produk Segar',
        'brand' => 'Farm Fresh',
        'price' => '3000',
        'qty' => '40',
        'status' => 'Out of Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Dishwashing Liquid',
        'desc' => 'Dishwashing liquid effectively removes grease and food residue from dishes, leaving them sparkling clean.',
        'category' => 'Produk Pembersih',
        'brand' => 'Sunlight',
        'price' => '6000',
        'qty' => '25',
        'status' => 'In Stock',
        'created_by' => 'reosta',
    ],
    [
        'name' => 'Band-Aid',
        'desc' => 'Band-Aid adhesive bandages are essential for covering and protecting minor cuts and wounds.',
        'category' => 'Produk Kesehatan',
        'brand' => 'Band-Aid',
        'price' => '3000',
        'qty' => '30',
        'status' => 'Out of Stock',
        'created_by' => 'reosta',
    ],
];
